default: &default
  secret_key_base: <%= ENV["RAILS_SECRET_KEY_BASE"] %>
  email_interceptor_recipients: ""

nemlogin: &nemlogin
  nemlogin_wsdl_uri: <%= ENV["NEMLOGIN_WSDL_URI"] %>
  nemlogin_login_uri: <%= ENV["NEMLOGIN_LOGIN_URI"] %>
  nemlogin_logout_uri: <%= ENV["NEMLOGIN_LOGOUT_URI"] %>
  nemlogin_mnemo: <%= ENV["NEMLOGIN_MNEMO"] %>

analytics: &analytics
  siteimprove_account_number: <%= ENV["SITEIMPROVE_ACCOUNT_NUMBER"] %>

maps: &maps
  map_tiles_provider: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'

apis: &apis
  microsoft_api_key: ""
  census_api_end_point: ""
  census_api_institution_code: ""
  census_api_portal_name: ""
  census_api_user_code: ""
  sms_end_point: ""
  sms_username: ""
  sms_password: ""

http_basic_auth: &http_basic_auth
  http_basic_auth: true

development:
  http_basic_username: "dev"
  http_basic_password: "pass"
  <<: *default
  <<: *maps
  <<: *nemlogin
  <<: *analytics

test:
  <<: *default
  <<: *maps
  <<: *nemlogin
  <<: *analytics

staging:
  secret_key_base: ""
  server_name: ""
  # mailer_delivery_method: "smtp"
  # smtp_settings:
  #   address: "smtp.example.com"
  #   port: 25
  #   domain: "your_domain.com"
  #   user_name: "<username>"
  #   password: "<password>"
  #   authentication: "plain"
  #   enable_starttls_auto: true
  force_ssl: true
  delay_jobs: true
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  <<: *default
  <<: *maps
  <<: *nemlogin
  <<: *apis
  <<: *analytics

preproduction:
  secret_key_base: ""
  server_name: ""
  # mailer_delivery_method: "smtp"
  # smtp_settings:
  #   address: "smtp.example.com"
  #   port: 25
  #   domain: "your_domain.com"
  #   user_name: "<username>"
  #   password: "<password>"
  #   authentication: "plain"
  #   enable_starttls_auto: true
  force_ssl: true
  delay_jobs: true
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  twitter_key: ""
  twitter_secret: ""
  facebook_key: ""
  facebook_secret: ""
  google_oauth2_key: ""
  google_oauth2_secret: ""
  <<: *maps
  <<: *nemlogin
  <<: *apis
  <<: *analytics

production:
  secret_key_base: ""
  server_name: ""
  # mailer_delivery_method: "smtp"
  # smtp_settings:
  #   address: "smtp.example.com"
  #   port: 25
  #   domain: "your_domain.com"
  #   user_name: "<username>"
  #   password: "<password>"
  #   authentication: "plain"
  #   enable_starttls_auto: true
  force_ssl: true
  delay_jobs: true
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  twitter_key: ""
  twitter_secret: ""
  facebook_key: ""
  facebook_secret: ""
  google_oauth2_key: ""
  google_oauth2_secret: ""
  <<: *maps
  <<: *nemlogin
  <<: *apis
  <<: *analytics
